Name: Training_Recipes
Type: ProjectFolder
Children:
- File: UI/UI.yaml
- File: Model/Model.yaml
- File: Converters/Converters.yaml
- File: Alarms/Alarms.yaml
- File: Recipes/Recipes.yaml
- File: Loggers/Loggers.yaml
- File: DataStores/DataStores.yaml
- File: Reports/Reports.yaml
- File: 'OPC-UA/OPC-UA.yaml'
- File: CommDrivers/CommDrivers.yaml
- File: NetLogic/NetLogic.yaml
- File: Security/Security.yaml
- File: Translations/Translations.yaml
- File: Retentivity/Retentivity.yaml
- File: AlarmTypes/AlarmTypes.yaml
- Name: PasswordPolicy
  Type: PasswordPolicy
  Children:
  - Name: MaximumPasswordAge
    Type: PropertyType
    DataType: UInt16
    Value: 0
  - Name: EnforcePasswordHistory
    Type: PropertyType
    DataType: Byte
    Value: 0
  - Name: MinimumPasswordAge
    Type: PropertyType
    DataType: UInt16
    Value: 0
  - Name: MinimumPasswordLength
    Type: PropertyType
    DataType: Byte
    Value: 0
- Name: RecipeSchema1
  Type: Alias
  DataType: NodeId
  Value: {"IdType":2,"Id":"ab7c09e3bea0f1418ff73c52275257ee","Namespace":22}
  Children:
  - Name: Kind
    Type: PropertyType
    DataType: NodeId
    Value: {"IdType":2,"Id":"ab7c09e3bea0f1418ff73c52275257ee","Namespace":22}
- Name: Authentication
  Type: PropertyGroup
  Children:
  - Name: DefaultUserFolder
    Type: NodePointer
    DataType: NodeId
    ReferenceType: HasProperty
    Value: {"IdType":2,"Id":"28fa632b2dd4c48ec853386dda4ef3cf","Namespace":22}
    Children:
    - Name: Kind
      Type: PropertyType
      DataType: NodeId
      Value: {"Id":61}
- Name: AlarmConfiguration
  Type: PropertyGroup
  Children:
  - Name: BranchingEnabled
    Type: BaseDataVariableType
    DataType: Boolean
    ReferenceType: HasProperty
    Value: false
- Name: Localization
  Type: PropertyGroup
  Children:
  - Name: Locales
    Type: BaseDataVariableType
    DataType: String
    ReferenceType: HasProperty
    ValueRank: OneDimension
    ArrayDimensions: [0]
    Value: ["en-US","it-IT"]
  - Name: LocaleFallbackList
    Type: BaseDataVariableType
    DataType: String
    ReferenceType: HasProperty
    ValueRank: OneDimension
    ArrayDimensions: [0]
    Value: ["en-US"]
